# Fibonacci Sequence:
# Write a program to print the Fibonacci sequence up to n terms using a while loop.

# 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144
# (0, i=0),(1 ,i=1), (1,i=2),(2,i=3),(5,i=4),(8,i=5)
# the fibonacci is the sum of the previous two numbers. e.g. the forth number is 2, add up two numbers(1, 1) together

x1, x2 = 0, 1


nTerms = int(input("Enter numbers of terms to get the Fibonacci sequence: " ))


#keep on track how many times has been loop
count = 1

while nTerms >= count:
    print(x1)
    #the third element can be generated by add up previous two numbers
    x3 = x1 + x2
    #re-assign the variables in prepare for the next loop
    x1 = x2
    x2 = x3
    #count increment in prepare for the next loop
    count += 1




